version: '3.7'
services:
  web:
    build: ./web/
    ports:
    - "8080:8080"
    environment:
    - APP_URL=http://app:8081/ping
  app:
    build: ./app/
    ports:
    - "8081:8081"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_database
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306